# convolution - 2d

Two dimensional convolution is really not that different from vector convolution. The same rules apply, we are just going to use them in the 2d case now. Do you remember what we said about convolution before?

**discrete convolution is a weighted overlap and add operation. **

*that's it.*

That still stands. I am going to explore 2d convolution using MATLAB.


### phase 1 - reiterating the rules of 1d convolution

The goal again is to create an ouput sequence (ok, ultimately matrix) based upon weighted overlap and add instructions.

I'll start off reiterating what we saw before:
* `targetToScale` is 'applied' to the output by a factor of `weightsByIndex[n]` for each `n`, meaning:
    *  `[2, 2]` is going to be applied to the first two positions of the output
    *  `[20, 20]` is going to be applied to the third and fourth positions
* the output length is going to be **4** - since `weightsByIndex` is length **3**, and a sequence of length **2** (`[20, 20]`) has to start there

In [1]:
weightsByIndex = [1, 0, 10]
targetToScale  = [2, 2]
convRes        = conv2( weightsByIndex, targetToScale )


weightsByIndex =

     1     0    10


targetToScale =

     2     2


convRes =

     2     2    20    20




I know this might seem like overkill, but understanding how the ouput is sized is actually important. One more example.

Let's use the same logic as before:
* `targetToScale` is 'applied' to the output by a factor of `weightsByIndex[n]` for each `n`, meaning:
    *  `[2, 2]` is going to be applied to positions one and two
    *  `[20, 20]` is going to be applied to positions two and three
    *  `[0, 0]` _i.e. the result of_ `0 * [2, 2]` is applied to positions three and four
* the output length is going to be **4** - since `weightsByIndex` is length **3**, and a sequence of length **2** (`[0, 0]`) has to start there

In [2]:
weightsByIndex = [1, 10, 0]
targetToScale  = [2, 2]
convRes        = conv2( weightsByIndex, targetToScale )


weightsByIndex =

     1    10     0


targetToScale =

     2     2


convRes =

     2    22    20     0




### phase 2 - moving to very simple 2-d convolution

So - let's start by convolving a column vector with a row vector. The result should be predictable based upon same rules from the previous example, but let's be explicit.

I'll start off reiterating what we saw before:
* `weightsByIndex` specifies where to 'apply' each scaled instance of `targetToScale` is 'applied' to the output by a factor of  for each `n`, meaning:
    *  the column vector `[2; 2]` is going to be applied at the **first** column of the first row of the output
    *  the column vector `[20; 20]` is going to be applied at the **second** column of the first row of the output
    *  the column vector `[0; 0]` is going to be applied at the **third** column of the first row of the output
* the output size is going to be **`(nRows=2, nCols=3)`** - since `weightsByIndex` is a row of length **3**, and a column of `nRows` **2** has to start at each position of the row

In [3]:
weightsByIndex = [1, 10, 0]
targetToScale  = [2; 2]
convRes        = conv2( weightsByIndex, targetToScale )


weightsByIndex =

     1    10     0


targetToScale =

     2
     2


convRes =

     2    20     0
     2    20     0




another example, this time `weightsByIndex` is going to be two rows long. The logic here is again that:

* `weightsByIndex` specifies (row, column) staring where positions of to 'apply' each scaled instance of `targetToScale`. Specifically:
    *  the column vector `[2; 2]` is going to be applied at the **first** column of the **first** row of the output
    *  the column vector `[20; 20]` is going to be applied at the **third** column of the **second** row of the output
    *  the column vector `[0; 0]` is going to be applied at all other starting positiions
* the output size is going to be **(nRows=3, nCols=3)** - since `weightsByIndex` is of size **(nRows=2, nCols=3)**, and a column of `nRows` **2** has to start at its final position

In [4]:
weightsByIndex = [1, 0, 0; 0, 0, 10]
targetToScale  = [2; 2]
convRes        = conv2( weightsByIndex, targetToScale )


weightsByIndex =

     1     0     0
     0     0    10


targetToScale =

     2
     2


convRes =

     2     0     0
     2     0    20
     0     0    20




in this example `weightsByIndex` is again going to be two rows long, but `targetToScale` will be a row vector. The result should be intuitive at this point, but I will be explict

* `weightsByIndex` again specifies (row, column) staring where positions of to 'apply' each scaled instance of `targetToScale`, and in this case:
    *  the row vector `[5, 5]` is going to be applied at the **first** column of the **first** row of the output
    *  the row vector `[50, 50]` is going to be applied at the **third** column of the **second** row of the output
    *  the row vector `[0, 0]` is going to be applied at all other starting positiions
* the output size is going to be **(nRows=2, nCols=4)** - since `weightsByIndex` is of size **(nRows=2, nCols=3)**, and a column of `nCols` **2** has to start at the final cell

In [5]:
weightsByIndex = [1, 0, 0; 0, 0, 10]
targetToScale  = [5, 5]
convRes        = conv2( weightsByIndex, targetToScale )


weightsByIndex =

     1     0     0
     0     0    10


targetToScale =

     5     5


convRes =

     5     5     0     0
     0     0    50    50




### phase 3 - slightly less simple very simple 2-d convolution

Ok, there had to be a point where this stuff started to get nuanced. It's easiest to explain with odd number of columns.

This example has a  `weightsByIndex` that is very much familiar, but `targetToScale` will be a column vector with `nCols=3`. According to our logic from the previous examples, the size of the result will be **(nRows=3, nCols=3)**, which it is.

The convolutions that we have performed to this point both in numpy and MATLAB are considered `'full'`, which means that the full entire result is computed and returned. The reality is that in many, arguably most, cases of convolution we don't care about the full result. The reason people don't care about everything is that convolution is **mathematical filtering**, and most times we only care about the subset of the result that corresponds to the filter operation. The greater implication is that - and you can't really see this from my simple examples - convolution is an operation in which the frequency spectrum of the first sequence is multiplicatively scaled by the frequency spectrum of the sequence. 

So, we're not going to talk about the **awesome** intricacies and possibilities of what it means to filter via convolution here. Sadly, this is just a pragmatic discussion of a mathematical process.

The key here is to highlight the difference between `'full'` and `'same'` sized operations. Full is what we talked about to this point. My intuition says you get it. `'same'` is a little more nuanced. Key Points:
* `weightsByIndex` has been renamed `sourceSignal` to imply that it is some source data in need of filtering. (It is still going to behave the same as before)
* `targetToScale` has been renamed `kernel` to imply that it is a convolution kernel with some characteristic that will project onto the source. (It also is going to behave the same as before)
* The `'same'` operation returns an output that is the same size as the first input to the `conv2` operation. You will notice that the result it not the fist row of `convResFull` though! This is because
    * the column vector `kernel` is going to be **centered** on each source signal data point before it is applied, with the implication that the indices of the `'full'` results are
```
(r=-1,c=0) (r=-1,c=1) (r=-1,c=2)
(r= 0,c=0) (r= 0,c=1) (r= 0,c=2)
(r= 1,c=0) (r= 1,c=1) (r= 1,c=2)
```
    * since the size of `sourceSignal` is **(nRows=1, nCols=3)**, the output will be size **(nRows=1, nCols=3)**, and we will only keep **row zero**

In [6]:
sourceSignal = [1, 0, 2]
kernel       = [1; 2 ;3]
convResFull  = conv2( sourceSignal, kernel , 'full')
convResSame  = conv2( sourceSignal, kernel , 'same')


sourceSignal =

     1     0     2


kernel =

     1
     2
     3


convResFull =

     1     0     2
     2     0     4
     3     0     6


convResSame =

     2     0     4




Here's another example that will highlight the difference between `'same'` and `'full'`, this time with a row vector kernel

The key here is to highlight the difference between `'full'` and `'same'` sized operations. Full is what we talked about to this point. My intuition says you get it. `'same'` is a little more nuanced. Key Points:

* the column vector `kernel` is again **centered** on each source signal data point before it is applied, but this time the centering is done with respect to the row, therefore
* the implication is that the indices of output of a `'full'` convolution are:
```
(r=0,c=-1) (r=0,c= 0) (r=0,c= 1) (r= 0,c=2) (r= 0,c=3) (r= 0,c=4) (r= 0,c=5)
```
* since the size of `sourceSignal` is (nRows=1, nCols=5), only columns zero through four, inclusive, are included in the `convResSame` result

In [7]:
sourceSignal = [1, 0, 0, 0, 5]
kernel       = [1, 2, 3]
convResFull  = conv2( sourceSignal, kernel , 'full')
convResSame  = conv2( sourceSignal, kernel , 'same')


sourceSignal =

     1     0     0     0     5


kernel =

     1     2     3


convResFull =

     1     2     3     0     5    10    15


convResSame =

     2     3     0     5    10




So what if you have a kernel that has both rows and columns?

Your answer plays by the rows and column rules that have been established.

Here are two straightforward examples where the results from the source signal are non-overlapping:

In [8]:
sourceSignal = [1, 0, 0, 0, 5]
kernel       = [1; 2; 3]*[1, 1, 1]
convResFull  = conv2( sourceSignal, kernel , 'full')
convResSame  = conv2( sourceSignal, kernel , 'same')


sourceSignal =

     1     0     0     0     5


kernel =

     1     1     1
     2     2     2
     3     3     3


convResFull =

     1     1     1     0     5     5     5
     2     2     2     0    10    10    10
     3     3     3     0    15    15    15


convResSame =

     2     2     0    10    10




In [9]:
sourceSignal = [1, 0, 0, 0, 0; 0, 0, 0, 0, 6]
kernel       = [1; 2; 3]*[1, 1, 1]
convResFull  = conv2( sourceSignal, kernel , 'full')
convResSame  = conv2( sourceSignal, kernel , 'same')


sourceSignal =

     1     0     0     0     0
     0     0     0     0     6


kernel =

     1     1     1
     2     2     2
     3     3     3


convResFull =

     1     1     1     0     0     0     0
     2     2     2     0     6     6     6
     3     3     3     0    12    12    12
     0     0     0     0    18    18    18


convResSame =

     2     2     0     6     6
     3     3     0    12    12




And finally is a slightly more complicated operation that puts is all together. There are no new rules here - so I'm not going to give an explanation. If the result is predicatable and makes sense, congratulations - you understand how to calculate a convolution!

In [10]:
sourceSignal = [1, 0, 0; 200, 0 30000]
kernel       = [1; 2; 3]*[1, 1, 1]
convResFull  = conv2( sourceSignal, kernel , 'full')
convResSame  = conv2( sourceSignal, kernel , 'same')


sourceSignal =

           1           0           0
         200           0       30000


kernel =

     1     1     1
     2     2     2
     3     3     3


convResFull =

           1           1           1           0           0
         202         202       30202       30000       30000
         403         403       60403       60000       60000
         600         600       90600       90000       90000


convResSame =

         202       30202       30000
         403       60403       60000


