# tf.nn.conv2d

#### demonstration of convolution in the context of tensorflow

## Part 1 - vector convolution using tf.nn.conv2d

* step 0 - import tensorflow!

In [1]:
import tensorflow as tf

when convolving a vector (not a matrix) like the simple examples before, we get predictable results (albeit reversed owing to the correlation implementation of convolution) 

#### Example 1: 
    * data has shape   (height=1, width=5)
    * kernel has shape (height=3, width=1)
    
**verdict: generates desired 1-d convolution result**

In [2]:
# batch_shape = [batch_size, in_height, in_width, in_channels]
x       = tf.constant([0, 0, 1, 0, 0], dtype=tf.float32)
x       = tf.reshape(x, [1, 1, 5, 1])

# kernel_shape = [width, height, n_channel_in, n_channel_out]
kernel  = tf.constant([2, 3, 4], dtype=tf.float32)
kernel  = tf.reshape(kernel, [1, 3, 1, 1])

conv_op = tf.nn.conv2d(x, kernel, strides=[1, 1, 1, 1], padding="SAME")

# to make it readable
reshape_op = tf.reshape(conv_op, [5])

print( "x shape:       {}".format( x.get_shape().as_list() ) )
print( "kernel shape:  {}".format( kernel.get_shape().as_list() ) )
print( "conv_op shape: {}\n".format( conv_op.get_shape().as_list() ) )

with tf.Session() as sess:
    print( sess.run(x), "\n\n" )
    print( sess.run(kernel), "\n\n" )
    print( sess.run(conv_op), "\n" )
    print( "===============\nresult:\n", sess.run(reshape_op) )

x shape:       [1, 1, 5, 1]
kernel shape:  [1, 3, 1, 1]
conv_op shape: [1, 1, 5, 1]

[[[[ 0.]
   [ 0.]
   [ 1.]
   [ 0.]
   [ 0.]]]] 


[[[[ 2.]]

  [[ 3.]]

  [[ 4.]]]] 


[[[[ 0.]
   [ 4.]
   [ 3.]
   [ 2.]
   [ 0.]]]] 

result:
 [ 0.  4.  3.  2.  0.]


#### Example 2: 
    * data has shape   (height=5, width=1)
    * kernel has shape (height=1, width=3)
    
**verdict: generates desired 1-d convolution result**

In [3]:
# batch_shape = [batch_size, in_height, in_width, in_channels]
x       = tf.constant([0, 0, 1, 0, 0], dtype=tf.float32)
x       = tf.reshape(x, [1, 5, 1, 1])

# kernel_shape = [width, height, n_channel_in, n_channel_out]
kernel  = tf.constant([2, 3, 4], dtype=tf.float32)
kernel  = tf.reshape(kernel, [3, 1, 1, 1])

conv_op = tf.nn.conv2d(x, kernel, strides=[1, 1, 1, 1], padding="SAME")

# to make it readable
reshape_op = tf.reshape(conv_op, [5])

print( "x shape:       {}".format( x.get_shape().as_list() ) )
print( "kernel shape:  {}".format( kernel.get_shape().as_list() ) )
print( "conv_op shape: {}\n".format( conv_op.get_shape().as_list() ) )

with tf.Session() as sess:
    print( sess.run(x), "\n\n" )
    print( sess.run(kernel), "\n\n" )
    print( sess.run(conv_op), "\n" )
    print( "===============\nresult:\n", sess.run(reshape_op) )

x shape:       [1, 5, 1, 1]
kernel shape:  [3, 1, 1, 1]
conv_op shape: [1, 5, 1, 1]

[[[[ 0.]]

  [[ 0.]]

  [[ 1.]]

  [[ 0.]]

  [[ 0.]]]] 


[[[[ 2.]]]


 [[[ 3.]]]


 [[[ 4.]]]] 


[[[[ 0.]]

  [[ 4.]]

  [[ 3.]]

  [[ 2.]]

  [[ 0.]]]] 

result:
 [ 0.  4.  3.  2.  0.]


#### Example 3:
    * data has shape   (height=5, width=1)
    * kernel has shape (height=3, width=1)
    
**verdict: does not generate desired 1-d convolution result**

In [4]:
# batch_shape = [batch_size, in_height, in_width, in_channels]
x       = tf.constant([0, 0, 1, 0, 0], dtype=tf.float32)
x       = tf.reshape(x, [1, 5, 1, 1])

# kernel_shape = [width, height, n_channel_in, n_channel_out]
kernel  = tf.constant([2, 3, 4], dtype=tf.float32)
kernel  = tf.reshape(kernel, [1, 3, 1, 1])

conv_op = tf.nn.conv2d(x, kernel, strides=[1, 1, 1, 1], padding="SAME")

# to make it readable
reshape_op = tf.reshape(conv_op, [5])

print( "x shape:       {}".format( x.get_shape().as_list() ) )
print( "kernel shape:  {}".format( kernel.get_shape().as_list() ) )
print( "conv_op shape: {}\n".format( conv_op.get_shape().as_list() ) )

with tf.Session() as sess:
    print( sess.run(x), "\n\n" )
    print( sess.run(kernel), "\n\n" )
    print( sess.run(conv_op), "\n" )
    print( "===============\nresult:\n", sess.run(reshape_op) )

x shape:       [1, 5, 1, 1]
kernel shape:  [1, 3, 1, 1]
conv_op shape: [1, 5, 1, 1]

[[[[ 0.]]

  [[ 0.]]

  [[ 1.]]

  [[ 0.]]

  [[ 0.]]]] 


[[[[ 2.]]

  [[ 3.]]

  [[ 4.]]]] 


[[[[ 0.]]

  [[ 0.]]

  [[ 3.]]

  [[ 0.]]

  [[ 0.]]]] 

result:
 [ 0.  0.  3.  0.  0.]


#### Example 4:
    * data has shape   (height=1, width=5)
    * kernel has shape (height=1, width=3)
    
**verdict: does not generate desired 1-d convolution result**

In [5]:
# batch_shape = [batch_size, in_height, in_width, in_channels]
x       = tf.constant([0, 0, 1, 0, 0], dtype=tf.float32)
x       = tf.reshape(x, [1, 1, 5, 1])

# kernel_shape = [width, height, n_channel_in, n_channel_out]
kernel  = tf.constant([2, 3, 4], dtype=tf.float32)
kernel  = tf.reshape(kernel, [3, 1, 1, 1])

conv_op = tf.nn.conv2d(x, kernel, strides=[1, 1, 1, 1], padding="SAME")

# to make it readable
reshape_op = tf.reshape(conv_op, [5])

print( "x shape:       {}".format( x.get_shape().as_list() ) )
print( "kernel shape:  {}".format( kernel.get_shape().as_list() ) )
print( "conv_op shape: {}\n".format( conv_op.get_shape().as_list() ) )

with tf.Session() as sess:
    print( sess.run(x), "\n\n" )
    print( sess.run(kernel), "\n\n" )
    print( sess.run(conv_op), "\n" )
    print( "===============\nresult:\n", sess.run(reshape_op) )

x shape:       [1, 1, 5, 1]
kernel shape:  [3, 1, 1, 1]
conv_op shape: [1, 1, 5, 1]

[[[[ 0.]
   [ 0.]
   [ 1.]
   [ 0.]
   [ 0.]]]] 


[[[[ 2.]]]


 [[[ 3.]]]


 [[[ 4.]]]] 


[[[[ 0.]
   [ 0.]
   [ 3.]
   [ 0.]
   [ 0.]]]] 

result:
 [ 0.  0.  3.  0.  0.]
