# tf.nn.conv2d

demonstration of convolution in the context of tensorflow

## Part 2 - matrix signal, vector kernel convolution using tf.nn.conv2d
* step 0 - import tensorflow!

In [1]:
import tensorflow as tf

#### Example 1:
* data has shape   (height=2, width=5)
* kernel has shape (height=3, width=1)

**verdict: generates desired 1-d convolution result**

In [20]:
arr  = [[1, 0, 0, 0, 0],[0, 10, 0, 0, 0]]
kern = [2, 3, 4]

# batch_shape = [batch_size, in_height, in_width, in_channels]
x       = tf.constant(arr, dtype=tf.float32)
x       = tf.reshape(x, [1, 2, 5, 1])

# kernel_shape = [width, height, n_channel_in, n_channel_out]
kernel  = tf.constant(kern, dtype=tf.float32)
kernel  = tf.reshape(kernel, [1, 3, 1, 1])

conv_op = tf.nn.conv2d(x, kernel, strides=[1, 1, 1, 1], padding="SAME")

# to make it readable
reshape_op = tf.reshape(conv_op, [2, 5])

print( "x shape:       {}".format( x.get_shape().as_list() ) )
print( "kernel shape:  {}".format( kernel.get_shape().as_list() ) )
print( "conv_op shape: {}\n".format( conv_op.get_shape().as_list() ) )

with tf.Session() as sess:
    print( sess.run(x), "\n------------" )
    print( sess.run(kernel), "\n------------" )
    print( sess.run(conv_op) )
    print( "===============\nresult:\n", sess.run(reshape_op) )

x shape:       [1, 2, 5, 1]
kernel shape:  [1, 3, 1, 1]
conv_op shape: [1, 2, 5, 1]

[[[[  1.]
   [  0.]
   [  0.]
   [  0.]
   [  0.]]

  [[  0.]
   [ 10.]
   [  0.]
   [  0.]
   [  0.]]]] 
------------
[[[[ 2.]]

  [[ 3.]]

  [[ 4.]]]] 
------------
[[[[  3.]
   [  2.]
   [  0.]
   [  0.]
   [  0.]]

  [[ 40.]
   [ 30.]
   [ 20.]
   [  0.]
   [  0.]]]]
result:
 [[  3.   2.   0.   0.   0.]
 [ 40.  30.  20.   0.   0.]]
