# tf.nn.softmax

### the softmax operation is computed across the rows.

In [1]:
import tensorflow as tf

In [2]:
x             = tf.ones([1, 6], tf.float32)
reshape_op_1  = tf.reshape(x, [2,3])
softmax_op_1  = tf.nn.softmax(reshape_op_1)

with tf.Session() as sess:
    print( sess.run(x) , "\n")
    print( sess.run(reshape_op_1) , "\n")
    print( sess.run(softmax_op_1) , "\n")

[[ 1.  1.  1.  1.  1.  1.]] 

[[ 1.  1.  1.]
 [ 1.  1.  1.]] 

[[ 0.33333334  0.33333334  0.33333334]
 [ 0.33333334  0.33333334  0.33333334]] 



In [3]:
reshape_op_2  = tf.reshape(x, [3,2])
softmax_op_2  = tf.nn.softmax(reshape_op_2)

with tf.Session() as sess:
    print( sess.run(x) , "\n")
    print( sess.run(reshape_op_2) , "\n")
    print( sess.run(softmax_op_2) , "\n")

[[ 1.  1.  1.  1.  1.  1.]] 

[[ 1.  1.]
 [ 1.  1.]
 [ 1.  1.]] 

[[ 0.5  0.5]
 [ 0.5  0.5]
 [ 0.5  0.5]] 

