In [3]:
import scipy
import numpy as np

In [5]:
arr1 = np.array( [[1, 1, 1],[1, 0, 1],[1, 1, 1]])

In [7]:
a = np.arange(25).reshape((5,5))

In [8]:
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [11]:
np.convolve(a,arr1)

ValueError: object too deep for desired array

In [13]:
print(arr1)

[[1 1 1]
 [1 0 1]
 [1 1 1]]


In [14]:
z = scipy.signal.convolve2d(arr1,a)
print(z)

AttributeError: module 'scipy' has no attribute 'signal'

In [15]:
import tensorflow as tf

In [17]:
a = tf.zeros(5,5)

In [19]:
a[4] = 1

TypeError: 'Tensor' object does not support item assignment

In [24]:
a = np.zeros((5,5))
kernel = np.array( [[1, 1, 1],[1, 0, 1],[1, 1, 1]])


In [ ]:
sess = tf.Session()


In [23]:
print(a)

[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]]
